#!/usr/bin/python
"""
Copyright (c) 2014, Intel Corporation

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

* Neither the name of Intel Corporation nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

@file    mobdat
@author  Mic Bowman
@date    2013-12-03

This is the main script for running the mobdat mobile data simulator.

"""

import sys, os
import logging, warnings

sys.path.append(os.path.join(os.environ.get("OPENSIM","/share/opensim"),"lib","python"))
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "lib")))

import json, argparse
import cmd, readline, traceback
import re

from mobdat.common.graph import Graph, Decoration
from mobdat.builder import WorldBuilder

DataBindings = None
logger = logging.getLogger(__name__)

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def ParseConfigurationFiles(cfiles) :
    config = {}
    for cfile in cfiles :
        try :
            config.update(json.load(open(cfile)))
        except IOError as detail :
            warnings.warn("Error parsing configuration file %s; IO error %s" % (cfile, str(detail)))
            sys.exit(-1)
        except ValueError as detail :
            warnings.warn("Error parsing configuration file %s; value error %s" % (cfile, str(detail)))
            sys.exit(-1)
        except NameError as detail :
            warnings.warn("Error parsing configuration file %s; name error %s" % (cfile, str(detail)))
            sys.exit(-1)
        except :
            warnings.warn('Error parsing configuration file %s; %s' % (cfile, sys.exc_info()[0]))
            sys.exit(-1)

    return config

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def SetupLoggers() :
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    logfile = filename=os.path.join(os.path.dirname(__file__), "../logs/tester.log")
    flog = logging.FileHandler(logfile, mode='w')
    flog.setFormatter(logging.Formatter('%(levelname)s [%(name)s] %(message)s'))
    logger.addHandler(flog)

    clog = logging.StreamHandler()
    #clog.addFilter(logging.Filter(name='mobdat'))
    clog.setFormatter(logging.Formatter('[%(name)s] %(message)s'))
    clog.setLevel(logging.WARN)
    logger.addHandler(clog)

# -----------------------------------------------------------------
# -----------------------------------------------------------------
class TestController(cmd.Cmd) :
    pformat = 'tester> '

    # -----------------------------------------------------------------
    def __init__(self, logger, settings) :
        cmd.Cmd.__init__(self)

        self.Settings = settings
        self.prompt = 'tester> '
        self.__Logger = logger

    # -----------------------------------------------------------------
    def postcmd(self, flag, line) :
        return flag

    # -----------------------------------------------------------------
    def _CompileName(self, pattern) :
        return re.compile('^' + pattern + '$', re.IGNORECASE)

    # -----------------------------------------------------------------
    def _DumpDict(self, info) :
        return json.dumps(info, indent=4, sort_keys=True)

    # -----------------------------------------------------------------
    def _DumpList(self, info) :
        return json.dumps(info, indent=4, sort_keys=True)

    # =================================================================
    # COMMANDS
    # =================================================================

    # -----------------------------------------------------------------
    def do_exec(self, args) :
        """
        exec -- Command to run a list of extension files
        """
        global DataBindings
        pargs = args.split()
        for cf in pargs :
            try :
                logger.info('loading extension file %s', cf)
                execfile(cf, DataBindings)
                logger.info('loaded extension file %s', cf)
            except :
                logger.warn('unhandled error processing extension file %s\n%s', cf, traceback.format_exc(10))

    # -----------------------------------------------------------------
    def do_clear(self, args) :
        """
        clear -- Command to clear world data
        """
        global DataBindings
        try :
            DataBindings['world'] = WorldBuilder.WorldBuilder()
            logger.info('reset world data')
        except :
            logger.warn('unhandled error processing extension file %s\n%s', cf, traceback.format_exc(10))

    # -----------------------------------------------------------------
    def do_load(self, args) :
        """
        load -- Command to load a data file
            load <filename>
        """
        global DataBindings
        pargs = args.split()
        try :
            cf = pargs[0] if len(pargs) == 1 else self.Settings["General"].get("WorldInfoFile","world.js")
            DataBindings['world'] = WorldBuilder.WorldBuilder.LoadFromFile(cf)
            logger.warn('loaded world data from file %s', cf)
        except :
            logger.warn('unhandled error processing extension file %s\n%s', cf, traceback.format_exc(10))

    # -----------------------------------------------------------------
    def do_save(self, args) :
        """
        save -- Command to save one of the graphs in a file
            save <filename>
        """
        global DataBindings
        pargs = args.split()
        try :
            cf = pargs[0] if len(pargs) == 1 else self.Settings["General"].get("WorldInfoFile","world.js")
            logger.info('saving world data in %s', cf)
            with open(cf, "w") as fp :
                json.dump(DataBindings['world'].Dump(), fp, indent=2, ensure_ascii=True)
            logger.warn('saved world data in file %s', cf)
        except :
            logger.warn('unhandled error saving world data to file %s\n%s', cf, traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_node(self, args) :
        """
        node -- Subcommand to operate on nodes in the road network database
            node dump [name]*
            node dumprel [name]*
            node list [namepattern] [nodetype]
            node near <x> <y> <distance>
            node eval name [fields]+
        """
        pargs = args.split()
        try :
            if pargs[0] == 'list' :
                pattern = self._CompileName(pargs[1] if len(pargs) >= 2 else '.*')
                nodetype = pargs[2] if len(pargs) == 3 else None
                for name, node in DataBindings['world'].IterNodes(pattern = pattern, nodetype = nodetype) :
                    print name

            elif pargs[0] == 'near' :
                xcoord = int(pargs[1])
                ycoord = int(pargs[2])
                dist = int(pargs[3])
                for node in DataBindings['world'].FindNodesInRange(xcoord, ycoord, dist) :
                    print node.Name

            elif pargs[0] == 'dump' :
                for name in pargs[1:] :
                    if name in DataBindings['world'].Nodes :
                        node = DataBindings['world'].Nodes[name]
                        print self._DumpDict(node.Dump())

            elif pargs[0] == 'dumprel' :
                for name in pargs[1:] :
                    if name in DataBindings['world'].Nodes :
                        node = DataBindings['world'].Nodes[name]
                        for edge in node.IterOutputEdges() :
                            print "{0}: {1} --> {2}".format(edge.NodeType.Name, name, edge.EndNode.Name)
                        for edge in node.IterInputEdges() :
                            print "{0}: {1} <-- {2}".format(edge.NodeType.Name, name, edge.StartNode.Name)

            elif pargs[0] == 'attr' :
                for name in pargs[1:] :
                    if name in DataBindings['world'].Nodes :
                        print self._DumpDict(DataBindings['world'].Nodes[name].DumpAttributes())

            elif pargs[0] == 'eval' :
                node = DataBindings['world'].FindNodeByName(pargs[1])
                for field in pargs[2:] :
                    node = getattr(node, field)

                    # if isinstance(node, Graph.GraphObject) :
                    #     node = node.Name if field == 'Name' else node.__getattr__(field)
                    # else :
                    #     node = getattr(node, field)

                if isinstance(node, Graph.GraphObject) or isinstance(node, Decoration.Decoration) :
                    print self._DumpDict(node.Dump())
                else :
                    print node

        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_edge(self, args) :
        """
        edge -- Subcommand to operation on edges in the world database
            edge dump [name]*
            edge list [namepattern]*
            edge eval name [fields]+
        """
        pargs = args.split()
        try :
            if pargs[0] == 'list' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for cname, edge in DataBindings['world'].IterEdges(pattern = pattern) :
                    print cname

            elif pargs[0] == 'dump' :
                for name in pargs[1:] :
                    if name in DataBindings['world'].Edges :
                        print self._DumpDict(DataBindings['world'].Edges[name].Dump())

            elif pargs[0] == 'eval' :
                gobj = DataBindings['world'].FindEdgeByName(pargs[1])
                for field in pargs[2:] :
                    gobj = getattr(gobj, field)

                if isinstance(gobj, Graph.GraphObject) or isinstance(gobj, Decoration.Decoration) :
                    print self._DumpDict(gobj.Dump())
                else :
                    print gobj
        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_people(self, args) :
        """
        people -- Subcommand to operate on people in the perinfo database
            people byemp [bizpattern]*
            people byjob [jobpattern]*
        """
        pargs = args.split()
        try :
            if pargs[0] == 'byemp' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for pname, person in DataBindings['world'].IterNodes(nodetype = 'Person') :
                    if pattern.match(person.EmployedBy.Name) :
                        print pname

            elif pargs[0] == 'byjob' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for pname, person in DataBindings['world'].IterNodes(nodetype = 'Person') :
                    if pattern.match(person.JobDescription.Name) :
                        print pname

            elif pargs[0] == 'jobs' :
                joblist = {}
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for pname, person in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Person') :
                    joblist[person.JobDescription.Name] = 1
                for jobname in joblist.iterkeys() :
                    print jobname

        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_person(self, args) :
        """
        person -- Subcommand to operate on a person
            person network name
            person pref name [keyword*]
        """
        pargs = args.split()
        try :
            if pargs[0] == 'network' :
                name = pargs[1]
                if name in DataBindings['world'].Nodes :
                    person = DataBindings['world'].Nodes[name]
                    for edge in person.IterOutputEdges(edgetype = 'ConnectedTo') :
                        print "{0} --> {1} : {2}".format(name, edge.EndNode.Name, edge.Weight.Weight)

            if pargs[0] == 'pref' :
                name = pargs[1]
                if name in DataBindings['world'].Nodes :
                    person = DataBindings['world'].Nodes[name]
                    for spattern in pargs[2:] :
                        pattern = self._CompileName(spattern)
                        for preference, weight in person.Preference.PreferenceMap.iteritems() :
                            if pattern.match(preference) :
                                print "{0} --> {1}".format(preference, weight)

        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_job(self, args) :
        """
        job -- Subcommand to examine a person's job
            job list [namepattern]*
            job salary [namepattern]*
        """
        pargs = args.split()
        try :
            if pargs[0] == 'list' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for pname, person in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Person') :
                    print "{0} --> {1} at {2}".format(pname, person.JobDescription.Name, person.EmployedBy.Name)
            elif pargs[0] == 'salary' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for pname, person in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Person') :
                    print "{0} --> {1}".format(pname, person.JobDescription.Salary)

        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_business(self, args) :
        """
        business -- Subcommand to operate on businesses in the bizinfo database
            business jobs [name]*
            business location [name]*
            business type [name]*
        """
        pargs = args.split()
        try :
            if pargs[0] == 'jobs' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for name, business in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Business') :
                    joblist = {}
                    for job, demand in business.EmploymentProfile.JobList.iteritems() :
                        joblist[job.Name] = demand

                    print name
                    print self._DumpDict(joblist)
                    print

            elif pargs[0] == 'location' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for name, business in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Business') :
                    print "{0} has type {1}".format(name, business.ResidesAt.Name)

            elif pargs[0] == 'type' :
                pattern = self._CompileName(pargs[1] if len(pargs) == 2 else '.*')
                for name, business in DataBindings['world'].IterNodes(pattern = pattern, nodetype = 'Business') :
                    print "{0} has type {1}".format(name, business.BusinessProfile.BusinessType)

        except :
            logger.warn('unhandled error\n%s', traceback.format_exc(5))

    # -----------------------------------------------------------------
    def do_exit(self, args) :
        """exit
        Shutdown the simulator and exit the command loop
        """

        self.__Logger.warn("shutting down")
        return True

    # -----------------------------------------------------------------
    def do_shutdown(self, args) :
        self.do_exit(args)

# -----------------------------------------------------------------
# -----------------------------------------------------------------
def InitializeDataBindings(settings) :
    world = WorldBuilder.WorldBuilder()

    global DataBindings
    DataBindings = {"world" : world}

# -----------------------------------------------------------------
# -----------------------------------------------------------------

def Main() :
    SetupLoggers()

    # parse out the configuration file first
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', help='configuration file for simulation settings', default=['settings.js'], nargs = '+')
    (options, remainder) = parser.parse_known_args()

    settings = ParseConfigurationFiles(options.config)
    InitializeDataBindings(settings)

    controller = TestController(logger, settings)
    controller.cmdloop()

if __name__ == '__main__':
    Main()
